include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: ignore
    deprecated_member_use: ignore
    avoid_print: ignore
    unnecessary_nullable_for_final_variable_declarations: ignore
