import 'package:flutter/material.dart';

class AppWords {
  static Map<String, Map<String, String>> words = {
    'en': {
      'hello': 'Hello',
      'receivables': 'RECEIVABLES',
      'payables': 'PAYABLES',
      'language': 'Language',
      'settings': 'Settings',
      'entitlements': 'Entitlements',
      'my_clients': 'My Clients',
      'search': 'Search',
      'recent_transactions': 'Recent Transactions',
      'no_transactions_yet': 'No transactions yet',
      'add_a_new_person': 'Add a new person',
      'enter_person_name': 'Enter person name',
      'save': 'Save',
      'clients': 'Clients',
      'no_people_yet': 'No people yet',
      'person': 'Person',
      'no_payables_found': 'No payables found',
      'no_receivables_found': 'No receivables found',
      'add_a_new_transaction': 'Add a new transaction',
      'enter_amount': 'Enter amount',
      'enter_description': 'Enter description',
      'is_debt': 'Is debt',
      'arabic_language': 'Arabic(اللغة العربية)',
      'chinese_language': 'Chinese(中文)',
      'english_language': 'English(English)',
    },
    'ar': {
      'hello': 'مرحبا',
      'receivables': 'المستحقات',
      'payables': 'المدفوعات',
      'language': 'اللغة',
      'settings': 'الإعدادات',
      'entitlements': 'الاستحقاقات',
      'my_clients': 'عملائي',
      'search': 'بحث',
      'recent_transactions': 'المعاملات الأخيرة',
      'no_transactions_yet': 'لا توجد معاملات بعد',
      'add_a_new_person': 'إضافة شخص جديد',
      'enter_person_name': 'أدخل اسم الشخص',
      'save': 'حفظ',
      'clients': 'العملاء',
      'no_people_yet': 'لا يوجد أشخاص بعد',
      'person': 'شخص',
      'no_payables_found': 'لم يتم العثور على مدفوعات',
      'no_receivables_found': 'لم يتم العثور على مستحقات',
      'add_a_new_transaction': 'إضافة معاملة جديدة',
      'enter_amount': 'أدخل المبلغ',
      'enter_description': 'أدخل الوصف',
      'is_debt': 'هل هو دين',
      'arabic_language': 'العربية(اللغة العربية)',
      'chinese_language': 'الصينية(中文)',
      'english_language': 'الإنجليزية(English)',
    },
    'zh': {
      'hello': '你好',
      'receivables': '应收',
      'payables': '应付',
      'language': '语言',
      'settings': '设置',
      'entitlements': '权益',
      'my_clients': '我的客户',
      'search': '搜索',
      'recent_transactions': '最近交易',
      'no_transactions_yet': '暂无交易',
      'add_a_new_person': '添加新人',
      'enter_person_name': '输入人员姓名',
      'save': '保存',
      'clients': '客户',
      'no_people_yet': '暂无人员',
      'person': '人员',
      'no_payables_found': '未找到应付款项',
      'no_receivables_found': '未找到应收款项',
      'add_a_new_transaction': '添加新交易',
      'enter_amount': '输入金额',
      'enter_description': '输入描述',
      'is_debt': '是否为债务',
      'arabic_language': '阿拉伯语(اللغة العربية)',
      'chinese_language': '中文(中文)',
      'english_language': '英语(English)',
    },
  };
}

String getword(BuildContext context, String key) {
  String language = Localizations.localeOf(context).languageCode;
  return AppWords.words[language]?[key] ?? key;
}
